<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Callbacks & Promises</title>
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script>
      let list = [];
      //callbacks
      $.get("https://jsonplaceholder.typicode.com/posts", (response) => {
        console.log(response);

        const id = 1;
        $.get(
          `https://jsonplaceholder.typicode.com/posts/${id}`,
          (response) => {
            console.log(`by id => `, response);

            $.get(
              `https://jsonplaceholder.typicode.com/posts/${id}/comments`,
              (response) => {
                console.log(`comments => `, response);
              }
            ).fail((err) => {
              console.log(err);
            });
          }
        ).fail((err) => {
          console.log(err);
        });
      }).fail((err) => {
        console.log(err);
      });
      //promises
      const postListPromise = new Promise((resolve, reject) => {
        $.get("https://jsonplaceholder.typicode.com/posts", (data) => {
          //   console.log("GET POSTS LIST Response => ", data);
          resolve(data);
        }).fail((err) => {
          reject(
            new Error(
              `Call failed for GET POST List Request with status ${err.status}`
            )
          );
        });
      });
      postListPromise
        .then((response) => {
          console.log(`call success`);
          console.log(`Then Response => `, response);
        })
        .catch((error) => {
          console.log(`call Failed`);
          console.log(`Catch Error => `, error);
        });
      //chaining promises
      const postDetailsPromise = (data) =>
        new Promise((resolve, reject) => {
          $.get(
            `https://jsonplaceholder.typicode.com/posts/${data[0].id}`,
            (data) => {
              resolve(data);
            }
          ).fail((err) => {
            reject(new Error(`Details Call failed and status ${err.status}`));
          });
        });
      postListPromise
        // .then((response)=> postDetailsPromise(response))
        .then(postDetailsPromise)
        .then((response) => {
          console.log(`call success`);
          console.log(`Post Details Response => `, response);
        })
        .catch((error) => {
          console.log(`call Failed`);
          console.log(`Catch Error => `, error);
        });
    </script>
  </head>
  <body></body>
</html>
